
.486                                                            ; Jeu d'insruction du 486
.model flat, stdcall
option casemap : none

; ¤=÷=¤=÷=¤=÷=¤=÷=¤=÷=¤=÷=¤=÷=¤=÷=¤=÷=¤=÷=¤=÷=¤=÷=¤=÷=¤=÷=¤=÷=¤=÷=¤=÷=¤=÷=¤

include \masm32\include\windows.inc
include \masm32\include\masm32.inc
include \masm32\include\gdi32.inc
include \masm32\include\user32.inc
include \masm32\include\kernel32.inc
include \masm32\include\Comctl32.inc
include \masm32\include\comdlg32.inc
include \masm32\include\shell32.inc
include \masm32\include\oleaut32.inc
include \masm32\include\ole32.inc
include \masm32\include\dialogs.inc

includelib \masm32\lib\masm32.lib
includelib \masm32\lib\gdi32.lib
includelib \masm32\lib\user32.lib
includelib \masm32\lib\kernel32.lib
includelib \masm32\lib\Comctl32.lib
includelib \masm32\lib\comdlg32.lib
includelib \masm32\lib\shell32.lib
includelib \masm32\lib\oleaut32.lib
includelib \masm32\lib\ole32.lib

; ¤=÷=¤=÷=¤=÷=¤=÷=¤=÷=¤=÷=¤=÷=¤=÷=¤=÷=¤=÷=¤=÷=¤=÷=¤=÷=¤=÷=¤=÷=¤=÷=¤=÷=¤=÷=¤

ClearBuffer PROTO :DWORD

; ¤=÷=¤=÷=¤=÷=¤=÷=¤=÷=¤=÷=¤=÷=¤=÷=¤=÷=¤=÷=¤=÷=¤=÷=¤=÷=¤=÷=¤=÷=¤=÷=¤=÷=¤=÷=¤

.const

CRLF        equ 10, 13

; ¤=÷=¤=÷=¤=÷=¤=÷=¤=÷=¤=÷=¤=÷=¤=÷=¤=÷=¤=÷=¤=÷=¤=÷=¤=÷=¤=÷=¤=÷=¤=÷=¤=÷=¤=÷=¤

.data

RudeBoy	    db "You're a rude boy !", 0
GoodBoy	    db "You're a good boy !", 0
Fuck	    db "Hmmm... you mustn't patch me !!!!", 0
Ttl	    db "...", 0	
Temp	    db "ASM_CLASS", 0

deci	    db "%d", 0
FileFilt    db "\*.exe", 0
Constante   db "08/02/2004", 0

; «««««««««««««««««««««««««««««««««««««««««««««««««««««««««««««««««««««««««

.data?

_FILE       WIN32_FIND_DATA <?>
_SYSTEMTIME SYSTEMTIME <?>
_FILETIME   FILETIME <?>
Directory   db 512 dup (?)
Buffer	    db 50 dup (?)
hInstance   HINSTANCE ?                                                    ; Instance
hSearch	    HANDLE ?
hIcon       HANDLE ?
hFile	    HANDLE ?
hMapping    dd ?
pMapping    dd ?

; ¤=÷=¤=÷=¤=÷=¤=÷=¤=÷=¤=÷=¤=÷=¤=÷=¤=÷=¤=÷=¤=÷=¤=÷=¤=÷=¤=÷=¤=÷=¤=÷=¤=÷=¤=÷=¤

; -------------------------------------------------------------------------
; EOF
; -------------------------------------------------------------------------
